[phases.setup]
nixPkgs = [
  "php82Packages.composer",
  "php82Extensions.intl",
  "php82Extensions.mbstring",
  "php82Extensions.pdo_mysql",
  "libmysqlclient"
]


[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php spark serve --host=0.0.0.0 --port=${PORT:-8080}"
